protect main and dev branches (#27)
* renaming (#18)

Co-authored-by: Orwa Watad <theorwa@gmail.com>

* reorganize app.ts (#19)

Co-authored-by: Orwa Watad <theorwa@gmail.com>

* KV integration (#20)

* kv integration

* fix warnings

* kv integration

* using .dev.vars instead .env & enhance the env interface

* env interface

---------

Co-authored-by: Orwa Watad <theorwa@gmail.com>

* naming (#21)

Co-authored-by: Orwa Watad <theorwa@gmail.com>

* container config (#22)

* naming

* container config

---------

Co-authored-by: Orwa Watad <theorwa@gmail.com>

* config (#23)

Co-authored-by: Orwa Watad <theorwa@gmail.com>

* types (#24)

Co-authored-by: Orwa Watad <theorwa@gmail.com>

* styling and scheduled entry point (#25)

Co-authored-by: Orwa Watad <theorwa@gmail.com>

* protect main and dev branches

* protect main and dev branches

* test

* pull request dev trigger ci

---------

Co-authored-by: Orwa Watad <theorwa@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,5 +1,3 @@
-# ci
-
 name: CI/CD for TypeScript Project
 
 on:
@@ -7,21 +5,43 @@ on:
     branches:
       - '**'
   pull_request:
+    types: [opened, reopened, synchronize, edited]
     branches:
       - main
+      - dev
 
 jobs:
   Build-and-Validate:
     runs-on: ubuntu-24.04
 
     steps:
-      - name: Validate Push to Main
+      - name: test
+        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
         run: |
-          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" && "${{ github.event.head_commit.committer.name }}" != "GitHub" ]]; then
-            echo "❌ Direct pushes to 'main' are not allowed. Use a Pull Request instead."
+          echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
+          echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
+          echo "github.base_ref: ${{ github.base_ref }}"
+          echo "github.head_ref: ${{ github.head_ref }}"
+          echo "github.event_name: ${{ github.event_name }}"
+          echo "github.ref: ${{ github.ref }}"
+
+      - name: Validate Push to main/dev
+        if: ${{ github.event_name == 'push' && github.base_ref == 'refs/heads/main' }}
+        run: |
+          echo "❌ Direct pushes to 'main' or 'dev' are not allowed. Use a Pull Request workflow instead."
+          exit 1
+
+      - name: Validate Pull Request
+        if: ${{ github.event_name == 'pull_request' }}
+        run: |
+          if [[ "${{ github.base_ref }}" == "main" && "${{ github.event.pull_request.head.ref }}" != "dev" ]]; then
+            echo "❌ Pull requests to 'main' are only allowed from the 'dev' branch."
+            exit 1
+          elif [[ "${{ github.base_ref }}" == "dev" && "${{ github.event.pull_request.head.ref }}" == "main" ]]; then
+            echo "❌ Pull requests to 'dev' cannot come from 'main'."
             exit 1
           else
-            echo "✅ Push to 'main' is allowed."
+            echo "✅ Pull request validation passed."
           fi
 
       - name: Checkout Code
@@ -34,7 +54,7 @@ jobs:
           key: ${{ runner.os }}-node-22-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-node-22
-          lookup-only: true # Ensures the cache is used for restore but not saved after the job
+          lookup-only: true
 
       - name: Setup Node.js
         uses: actions/setup-node@v3
